navbar:
  - events: /collections/events.html
  - manifesto: /collections/manifesto.html
  - design: /collections/design.html
  - gallery: /gallery.html
  - members: /members.html
  - about: /about.html
baseURL: https://anirudhsudhir.github.io/test-hsp/
siteTitle: "HSP"
siteScripts:
author: HSP
themeURL: "/static/style.css"
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International."
